use crate::request::{request_type_name, request_views};
use crate::util::{
    collect_type_idents, handler_mod_name, handler_name, pretty, rust_ident, rust_type,
};
use ast::{ApiFile, Route};
use quote::quote;
use syn::Ident;

pub(crate) fn has_routes(ast: &ApiFile) -> bool {
    ast.services
        .iter()
        .any(|service| !service.routes.is_empty())
}

pub(crate) fn render_mod(ast: &ApiFile) -> String {
    let mods: Vec<Ident> = unique_routes(ast)
        .into_iter()
        .map(handler_mod_name)
        .collect();
    pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            #(pub mod #mods;)*
            #(pub use #mods::*;)*
        },
    )
}

pub(crate) fn render_files(ast: &ApiFile) -> Vec<(String, String)> {
    unique_routes(ast)
        .into_iter()
        .map(|route| {
            let module = handler_mod_name(route);
            (
                format!("src/handlers/{module}.rs"),
                render_handler_file(ast, route),
            )
        })
        .collect()
}

fn unique_routes(ast: &ApiFile) -> Vec<&Route> {
    let mut seen = Vec::new();
    let mut routes = Vec::new();
    for service in &ast.services {
        for route in &service.routes {
            let module = handler_mod_name(route).to_string();
            if !seen.contains(&module) {
                seen.push(module);
                routes.push(route);
            }
        }
    }
    routes
}

fn render_handler_file(ast: &ApiFile, route: &Route) -> String {
    let mut named_types = Vec::new();
    let mut extractors = Vec::new();
    collect_handler_types(ast, route, &mut named_types, &mut extractors);
    let types_use = (!named_types.is_empty()).then(|| {
        quote!(use crate::types::{#(#named_types),*};)
    });
    let extract_use = (!extractors.is_empty()).then(|| {
        quote!(use rest::{#(#extractors),*};)
    });
    let handler = render_handler(ast, route);
    pretty(
        "// Code scaffolded by rust-zero. Safe to edit.\n\n",
        quote! {
            #types_use
            use actix_web::web;
            #extract_use
            #handler
        },
    )
}

fn collect_handler_types(
    ast: &ApiFile,
    route: &Route,
    named_types: &mut Vec<Ident>,
    extractors: &mut Vec<Ident>,
) {
    collect_type_idents(route.returns.as_ref(), named_types);
    let Some(request) = &route.request else {
        return;
    };
    let Some(name) = request_type_name(request) else {
        collect_type_idents(Some(request), named_types);
        push_ident(extractors, rust_ident("ValidatedJson"));
        return;
    };
    match request_views(ast, name) {
        Some(views) if !views.is_json_only() => {
            if !views.path.is_empty() {
                push_ident(named_types, views.view_ident("Path"));
                push_ident(extractors, rust_ident("ValidatedPath"));
            }
            if !views.query.is_empty() {
                push_ident(named_types, views.view_ident("Query"));
                push_ident(extractors, rust_ident("ValidatedQuery"));
            }
            if !views.headers.is_empty() {
                push_ident(named_types, views.view_ident("Headers"));
                push_ident(extractors, rust_ident("ValidatedHeader"));
            }
            if !views.form.is_empty() {
                push_ident(named_types, views.view_ident("Form"));
                push_ident(extractors, rust_ident("ValidatedForm"));
            }
            if !views.json.is_empty() {
                push_ident(named_types, views.view_ident("Body"));
                push_ident(extractors, rust_ident("ValidatedJson"));
            }
        }
        _ => {
            push_ident(named_types, rust_ident(name));
            push_ident(extractors, rust_ident("ValidatedJson"));
        }
    }
}

fn render_handler(ast: &ApiFile, route: &Route) -> proc_macro2::TokenStream {
    let name = handler_name(route);
    let args = request_args(ast, route);
    let ret = match &route.returns {
        Some(ty) => {
            let ty = rust_type(ty);
            quote!(web::Json<#ty>)
        }
        None => quote!(web::Json<()>),
    };
    let todo_msg = format!("implement {name}");
    quote! {
        pub async fn #name(#(#args),*) -> #ret {
            todo!(#todo_msg)
        }
    }
}

fn request_args(ast: &ApiFile, route: &Route) -> Vec<proc_macro2::TokenStream> {
    let Some(request) = &route.request else {
        return Vec::new();
    };
    let Some(name) = request_type_name(request) else {
        let ty = rust_type(request);
        return vec![quote!(_req: ValidatedJson<#ty>)];
    };
    match request_views(ast, name) {
        Some(views) if !views.is_json_only() => {
            let mut args = Vec::new();
            if !views.path.is_empty() {
                let ty = views.view_ident("Path");
                args.push(quote!(_path: ValidatedPath<#ty>));
            }
            if !views.query.is_empty() {
                let ty = views.view_ident("Query");
                args.push(quote!(_query: ValidatedQuery<#ty>));
            }
            if !views.headers.is_empty() {
                let ty = views.view_ident("Headers");
                args.push(quote!(_headers: ValidatedHeader<#ty>));
            }
            if !views.form.is_empty() {
                let ty = views.view_ident("Form");
                args.push(quote!(_form: ValidatedForm<#ty>));
            }
            if !views.json.is_empty() {
                let ty = views.view_ident("Body");
                args.push(quote!(_body: ValidatedJson<#ty>));
            }
            args
        }
        _ => {
            let ty = rust_ident(name);
            vec![quote!(_req: ValidatedJson<#ty>)]
        }
    }
}

fn push_ident(names: &mut Vec<Ident>, ident: Ident) {
    if !names.iter().any(|existing| existing == &ident) {
        names.push(ident);
    }
}
