use crate::request::{request_type_name, request_views};
use crate::util::{
    collect_type_idents, handler_name, pretty, rust_ident, rust_type, service_mod_name,
};
use ast::{ApiFile, Route, Service};
use quote::quote;
use syn::Ident;

pub(crate) fn has_routes(ast: &ApiFile) -> bool {
    ast.services
        .iter()
        .any(|service| !service.routes.is_empty())
}

pub(crate) fn render_mod(ast: &ApiFile) -> String {
    let mods: Vec<Ident> = grouped_services(ast)
        .into_iter()
        .map(|(name, _)| service_mod_name(name))
        .collect();
    pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            #(pub mod #mods;)*
            #(pub use #mods::*;)*
        },
    )
}

pub(crate) fn render_files(ast: &ApiFile) -> Vec<(String, String)> {
    grouped_services(ast)
        .into_iter()
        .map(|(name, services)| {
            let module = service_mod_name(name);
            (
                format!("src/handlers/{module}.rs"),
                render_service_file(ast, &services),
            )
        })
        .collect()
}

fn grouped_services(ast: &ApiFile) -> Vec<(&str, Vec<&Service>)> {
    let mut groups: Vec<(&str, Vec<&Service>)> = Vec::new();
    for service in &ast.services {
        if service.routes.is_empty() {
            continue;
        }
        if let Some((_, existing)) = groups
            .iter_mut()
            .find(|(name, _)| *name == service.name.as_str())
        {
            existing.push(service);
        } else {
            groups.push((service.name.as_str(), vec![service]));
        }
    }
    groups
}

fn render_service_file(ast: &ApiFile, services: &[&Service]) -> String {
    let mut named_types = Vec::new();
    let mut extractors = Vec::new();
    for service in services {
        for route in &service.routes {
            collect_handler_types(ast, route, &mut named_types, &mut extractors);
        }
    }
    let types_use = (!named_types.is_empty()).then(|| {
        quote!(use crate::types::{#(#named_types),*};)
    });
    let extract_use = (!extractors.is_empty()).then(|| {
        quote!(use rest::{#(#extractors),*};)
    });
    let handlers = services.iter().flat_map(|service| {
        service
            .routes
            .iter()
            .map(|route| render_handler(ast, route))
    });
    pretty(
        "// Code scaffolded by rust-zero. Safe to edit.\n\n",
        quote! {
            #types_use
            use actix_web::web;
            #extract_use
            #(#handlers)*
        },
    )
}

fn collect_handler_types(
    ast: &ApiFile,
    route: &Route,
    named_types: &mut Vec<Ident>,
    extractors: &mut Vec<Ident>,
) {
    collect_type_idents(route.returns.as_ref(), named_types);
    let Some(request) = &route.request else {
        return;
    };
    let Some(name) = request_type_name(request) else {
        collect_type_idents(Some(request), named_types);
        push_ident(extractors, rust_ident("ValidatedJson"));
        return;
    };
    push_ident(named_types, rust_ident(name));
    if request_views(ast, name).is_none_or(|views| views.is_json_only()) {
        push_ident(extractors, rust_ident("ValidatedJson"));
    }
}

fn render_handler(ast: &ApiFile, route: &Route) -> proc_macro2::TokenStream {
    let name = handler_name(route);
    let args = request_args(ast, route);
    let ret = match &route.returns {
        Some(ty) => {
            let ty = rust_type(ty);
            quote!(web::Json<#ty>)
        }
        None => quote!(web::Json<()>),
    };
    let todo_msg = format!("implement {name}");
    quote! {
        pub async fn #name(#(#args),*) -> #ret {
            todo!(#todo_msg)
        }
    }
}

fn request_args(ast: &ApiFile, route: &Route) -> Vec<proc_macro2::TokenStream> {
    let Some(request) = &route.request else {
        return Vec::new();
    };
    let Some(name) = request_type_name(request) else {
        let ty = rust_type(request);
        return vec![quote!(_req: ValidatedJson<#ty>)];
    };
    let ty = rust_ident(name);
    if request_views(ast, name).is_some_and(|views| views.is_mixed()) {
        vec![quote!(_req: #ty)]
    } else {
        vec![quote!(_req: ValidatedJson<#ty>)]
    }
}

fn push_ident(names: &mut Vec<Ident>, ident: Ident) {
    if !names.iter().any(|existing| existing == &ident) {
        names.push(ident);
    }
}
