use crate::util::{
    actix_path, duration_to_ms, handler_name, join_path, method_builder, method_name,
    normalize_prefix, pretty,
};
use ast::{ApiFile, AtServer, Service};
use quote::quote;
use syn::{Ident, LitInt, LitStr};

pub(crate) fn render(ast: &ApiFile) -> String {
    let mut handlers = Vec::<Ident>::new();
    for service in &ast.services {
        for route in &service.routes {
            let name = handler_name(route);
            if !handlers.iter().any(|existing| existing == &name) {
                handlers.push(name);
            }
        }
    }
    let handlers_use = (!handlers.is_empty()).then(|| {
        quote!(use crate::handlers::{#(#handlers),*};)
    });

    let route_stmts: Vec<_> = ast
        .services
        .iter()
        .flat_map(|service| {
            let prefix = service_prefix(service);
            service.routes.iter().map(move |route| {
                let path = join_path(&prefix, &actix_path(&route.path));
                let method = method_builder(route.method);
                let handler = handler_name(route);
                quote! {
                    cfg.route(#path, #method.to(#handler));
                }
            })
        })
        .collect();

    let body = if route_stmts.is_empty() {
        quote!(let _ = cfg;)
    } else {
        quote!(#(#route_stmts)*)
    };

    let groups = ast.services.iter().filter_map(render_group);

    pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            use actix_web::web;
            use rest::{RouteGroupConfig, RoutePolicyConfig};
            #handlers_use
            pub fn configure(cfg: &mut web::ServiceConfig) {
                #body
            }
            pub fn route_groups() -> Vec<RouteGroupConfig> {
                vec![#(#groups),*]
            }
        },
    )
}

fn render_group(service: &Service) -> Option<proc_macro2::TokenStream> {
    if service.routes.is_empty() {
        return None;
    }
    let prefix = service_prefix(service);
    let mut extras = Vec::new();
    if let Some(ms) = server_item(service.server.as_ref(), "timeout").and_then(duration_to_ms) {
        let lit = LitInt::new(&ms.to_string(), proc_macro2::Span::call_site());
        extras.push(quote!(timeout_ms: Some(#lit)));
    }
    if let Some(bytes) = server_item(service.server.as_ref(), "maxBytes")
        .and_then(|raw| raw.parse::<usize>().ok())
    {
        let lit = LitInt::new(&bytes.to_string(), proc_macro2::Span::call_site());
        extras.push(quote!(max_body_bytes: Some(#lit)));
    }
    if let Some(raw) = server_item(service.server.as_ref(), "middleware") {
        let names: Vec<_> = raw
            .split(',')
            .map(str::trim)
            .filter(|name| !name.is_empty())
            .map(|name| LitStr::new(name, proc_macro2::Span::call_site()))
            .collect();
        if !names.is_empty() {
            extras.push(quote!(middleware: vec![#(#names.to_owned()),*]));
        }
    }

    let routes = service.routes.iter().map(|route| {
        let method = method_name(route.method);
        let path = actix_path(&route.path);
        quote! {
            RoutePolicyConfig {
                method: #method.to_owned(),
                path: #path.to_owned(),
                public: true,
                jwt: None,
                timeout_ms: None,
                max_body_bytes: None,
                priority: None,
                sse: None,
            }
        }
    });

    Some(quote! {
        RouteGroupConfig {
            prefix: #prefix.to_owned(),
            #(#extras,)*
            routes: vec![#(#routes),*],
            ..RouteGroupConfig::default()
        }
    })
}

fn service_prefix(service: &Service) -> String {
    server_item(service.server.as_ref(), "prefix")
        .map(normalize_prefix)
        .unwrap_or_default()
}

fn server_item<'a>(server: Option<&'a AtServer>, key: &str) -> Option<&'a str> {
    server.and_then(|server| {
        server
            .items
            .iter()
            .find(|item| item.key == key)
            .map(|item| item.value.as_str())
    })
}
