use crate::util::{
    actix_path, duration_to_ms, handler_name, join_path, method_builder, method_name,
    normalize_prefix, pretty, rust_ident, to_snake,
};
use ast::{ApiFile, AtServer, Service};
use quote::quote;
use syn::{Ident, LitInt, LitStr};

pub(crate) fn render(ast: &ApiFile) -> String {
    let mut handlers = Vec::<Ident>::new();
    for service in &ast.services {
        for route in &service.routes {
            let name = handler_name(route);
            if !handlers.iter().any(|existing| existing == &name) {
                handlers.push(name);
            }
        }
    }
    let handlers_use = (!handlers.is_empty()).then(|| {
        quote!(use crate::handlers::{#(#handlers),*};)
    });

    let route_stmts: Vec<_> = ast
        .services
        .iter()
        .flat_map(|service| {
            let prefix = service_prefix(service);
            service.routes.iter().map(move |route| {
                let path = join_path(&prefix, &actix_path(&route.path));
                let method = method_builder(route.method);
                let handler = handler_name(route);
                quote! {
                    cfg.route(#path, #method.to(#handler));
                }
            })
        })
        .collect();

    let body = if route_stmts.is_empty() {
        quote!(let _ = cfg;)
    } else {
        quote!(#(#route_stmts)*)
    };

    let mut used_names = Vec::new();
    let groups: Vec<_> = ast
        .services
        .iter()
        .filter_map(|service| {
            let name = group_ident(service, &mut used_names)?;
            render_group(&name, service)
        })
        .collect();
    let group_names = used_names.clone();

    pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            use actix_web::web;
            use rest::{RouteGroupConfig, RoutePolicyConfig};

            #handlers_use

            pub fn configure(cfg: &mut web::ServiceConfig) {
                #body
            }

            pub fn route_groups() -> Vec<RouteGroupConfig> {
                #(#groups)*
                vec![#(#group_names),*]
            }
        },
    )
}

fn group_ident(service: &Service, used: &mut Vec<Ident>) -> Option<Ident> {
    if service.routes.is_empty() {
        return None;
    }
    let mut base = to_snake(&service.name);
    if base.is_empty() {
        base = "group".into();
    }
    if base.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        base = format!("group_{base}");
    }
    let mut name = rust_ident(&base);
    let mut idx = 2;
    while used.iter().any(|existing| existing == &name) {
        name = rust_ident(&format!("{base}_{idx}"));
        idx += 1;
    }
    used.push(name.clone());
    Some(name)
}

fn render_group(name: &Ident, service: &Service) -> Option<proc_macro2::TokenStream> {
    if service.routes.is_empty() {
        return None;
    }

    let mut fields = Vec::new();
    let prefix = service_prefix(service);
    if !prefix.is_empty() {
        fields.push(quote!(prefix: #prefix.to_owned()));
    }
    if let Some(ms) = server_item(service.server.as_ref(), "timeout").and_then(duration_to_ms) {
        let lit = LitInt::new(&ms.to_string(), proc_macro2::Span::call_site());
        fields.push(quote!(timeout_ms: Some(#lit)));
    }
    if let Some(bytes) = server_item(service.server.as_ref(), "maxBytes")
        .and_then(|raw| raw.parse::<usize>().ok())
    {
        let lit = LitInt::new(&bytes.to_string(), proc_macro2::Span::call_site());
        fields.push(quote!(max_body_bytes: Some(#lit)));
    }
    if let Some(raw) = server_item(service.server.as_ref(), "middleware") {
        let names: Vec<_> = raw
            .split(',')
            .map(str::trim)
            .filter(|item| !item.is_empty())
            .map(|item| LitStr::new(item, proc_macro2::Span::call_site()))
            .collect();
        if !names.is_empty() {
            fields.push(quote!(middleware: vec![#(#names.to_owned()),*]));
        }
    }

    let routes = service.routes.iter().map(|route| {
        let method = method_name(route.method);
        let path = actix_path(&route.path);
        quote!(RoutePolicyConfig::public(#method, #path))
    });
    fields.push(quote!(routes: vec![#(#routes),*]));

    Some(quote! {
        let #name = RouteGroupConfig {
            #(#fields,)*
            ..RouteGroupConfig::default()
        };
    })
}

fn service_prefix(service: &Service) -> String {
    server_item(service.server.as_ref(), "prefix")
        .map(normalize_prefix)
        .unwrap_or_default()
}

fn server_item<'a>(server: Option<&'a AtServer>, key: &str) -> Option<&'a str> {
    server.and_then(|server| {
        server
            .items
            .iter()
            .find(|item| item.key == key)
            .map(|item| item.value.as_str())
    })
}
