use crate::request::{attr_value, field_location, request_type_name, request_views, Location, RequestViews};
use crate::util::{json_rename, pretty, rust_ident, rust_type, type_needs_hashmap};
use crate::validate::{self, GenerateError};
use ast::{ApiFile, Field, TypeDef};
use quote::quote;
use syn::Ident;

pub(crate) fn render(ast: &ApiFile) -> Result<String, GenerateError> {
    let needs_hashmap = ast
        .types
        .iter()
        .flat_map(|def| def.fields.iter())
        .any(|field| type_needs_hashmap(&field.ty));
    let hashmap_use = needs_hashmap.then(|| quote!(use std::collections::HashMap;));
    let views: Vec<RequestViews<'_>> = ast
        .types
        .iter()
        .filter(|def| is_request_type(ast, &def.name))
        .filter_map(|def| request_views(ast, &def.name))
        .collect();
    let needs_validate = views.iter().any(|view| {
        view.is_json_only()
            || !view.path.is_empty()
            || !view.query.is_empty()
            || !view.headers.is_empty()
            || !view.form.is_empty()
            || !view.json.is_empty()
    });
    let needs_validation_helper = views.iter().any(|view| {
        if view.is_json_only() {
            validate::has_validate_rules(&view.original.fields)
        } else {
            validate::has_validate_rules(view.path.iter().copied())
                || validate::has_validate_rules(view.query.iter().copied())
                || validate::has_validate_rules(view.headers.iter().copied())
                || validate::has_validate_rules(view.form.iter().copied())
                || validate::has_validate_rules(view.json.iter().copied())
        }
    });
    let validate_use = needs_validate.then(|| {
        if needs_validation_helper {
            quote!(use rust_zero_core::{Validate, Validation, ValidationErrors};)
        } else {
            quote!(use rust_zero_core::Validate;)
        }
    });
    let header_use = views.iter().any(|view| !view.headers.is_empty()).then(|| {
        quote! {
            use actix_web::http::header::HeaderMap;
            use rest::FromRequestHeaders;
        }
    });
    let mixed_extractors = mixed_extractor_idents(&views);
    let request_use = (!mixed_extractors.is_empty()).then(|| {
        quote! {
            use actix_web::{dev::Payload, Error, FromRequest, HttpRequest};
            use rest::{#(#mixed_extractors),*};
            use std::pin::Pin;
        }
    });

    let mut items = Vec::new();
    for def in &ast.types {
        items.push(render_struct(def, json_field_rename));
        if let Some(view) = views.iter().find(|view| view.original.name == def.name) {
            if view.is_json_only() {
                items.push(render_validate(
                    &def.name,
                    &rust_ident(&def.name),
                    &def.fields.iter().collect::<Vec<_>>(),
                )?);
            } else {
                items.extend(render_views(view)?);
                items.push(render_from_request(view));
            }
        }
    }

    Ok(pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            #header_use
            #request_use
            #validate_use
            use serde::{Deserialize, Serialize};
            #hashmap_use

            #(#items)*
        },
    ))
}

fn render_struct(
    def: &TypeDef,
    rename: impl Fn(&Field) -> Option<String>,
) -> proc_macro2::TokenStream {
    let name = rust_ident(&def.name);
    let fields = def.fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let ty = rust_type(&field.ty);
        let rename = rename(field).map(|rename| quote!(#[serde(rename = #rename)]));
        quote! {
            #rename
            pub #fname: #ty,
        }
    });
    quote! {
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct #name {
            #(#fields)*
        }
    }
}

fn render_views(views: &RequestViews<'_>) -> Result<Vec<proc_macro2::TokenStream>, GenerateError> {
    let mut items = Vec::new();
    push_view(
        &mut items,
        views.original.name.as_str(),
        views.view_ident("Path"),
        &views.path,
        Location::Path,
    )?;
    push_view(
        &mut items,
        views.original.name.as_str(),
        views.view_ident("Query"),
        &views.query,
        Location::Query,
    )?;
    push_view(
        &mut items,
        views.original.name.as_str(),
        views.view_ident("Headers"),
        &views.headers,
        Location::Header,
    )?;
    push_view(
        &mut items,
        views.original.name.as_str(),
        views.view_ident("Form"),
        &views.form,
        Location::Form,
    )?;
    push_view(
        &mut items,
        views.original.name.as_str(),
        views.view_ident("Body"),
        &views.json,
        Location::Json,
    )?;
    Ok(items)
}

fn push_view(
    items: &mut Vec<proc_macro2::TokenStream>,
    type_name: &str,
    name: Ident,
    fields: &[&Field],
    location: Location,
) -> Result<(), GenerateError> {
    if fields.is_empty() {
        return Ok(());
    }
    let field_tokens = fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let ty = rust_type(&field.ty);
        let rename = extractor_rename(field, location)
            .map(|rename| quote!(#[serde(rename = #rename)]));
        quote! {
            #rename
            pub #fname: #ty,
        }
    });
    items.push(quote! {
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct #name {
            #(#field_tokens)*
        }
    });
    items.push(render_validate(type_name, &name, fields)?);
    if location == Location::Header {
        items.push(render_from_headers(&name, fields));
    }
    Ok(())
}

fn mixed_extractor_idents(views: &[RequestViews<'_>]) -> Vec<Ident> {
    let mut names = Vec::new();
    for view in views {
        if !view.is_mixed() {
            continue;
        }
        if !view.path.is_empty() {
            push_ident(&mut names, rust_ident("ValidatedPath"));
        }
        if !view.query.is_empty() {
            push_ident(&mut names, rust_ident("ValidatedQuery"));
        }
        if !view.headers.is_empty() {
            push_ident(&mut names, rust_ident("ValidatedHeader"));
        }
        if !view.form.is_empty() {
            push_ident(&mut names, rust_ident("ValidatedForm"));
        }
        if !view.json.is_empty() {
            push_ident(&mut names, rust_ident("ValidatedJson"));
        }
    }
    names
}

fn push_ident(names: &mut Vec<Ident>, ident: Ident) {
    if !names.iter().any(|existing| existing == &ident) {
        names.push(ident);
    }
}

fn render_from_request(views: &RequestViews<'_>) -> proc_macro2::TokenStream {
    let name = rust_ident(&views.original.name);
    let mut extracts = Vec::new();
    let mut awaits = Vec::new();
    if !views.path.is_empty() {
        let ty = views.view_ident("Path");
        extracts.push(quote! {
            let path = ValidatedPath::<#ty>::from_request(request, payload);
        });
        awaits.push(quote! {
            let path = path.await?.0;
        });
    }
    if !views.query.is_empty() {
        let ty = views.view_ident("Query");
        extracts.push(quote! {
            let query = ValidatedQuery::<#ty>::from_request(request, payload);
        });
        awaits.push(quote! {
            let query = query.await?.0;
        });
    }
    if !views.headers.is_empty() {
        let ty = views.view_ident("Headers");
        extracts.push(quote! {
            let headers = ValidatedHeader::<#ty>::from_request(request, payload);
        });
        awaits.push(quote! {
            let headers = headers.await?.0;
        });
    }
    if !views.form.is_empty() {
        let ty = views.view_ident("Form");
        extracts.push(quote! {
            let form = ValidatedForm::<#ty>::from_request(request, payload);
        });
        awaits.push(quote! {
            let form = form.await?.0;
        });
    }
    if !views.json.is_empty() {
        let ty = views.view_ident("Body");
        extracts.push(quote! {
            let body = ValidatedJson::<#ty>::from_request(request, payload);
        });
        awaits.push(quote! {
            let body = body.await?.0;
        });
    }
    let assigns = views.original.fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let value = match field_location(field) {
            Location::Path => quote!(path.#fname),
            Location::Query => quote!(query.#fname),
            Location::Header => quote!(headers.#fname),
            Location::Form => quote!(form.#fname),
            Location::Json => quote!(body.#fname),
        };
        quote! { #fname: #value }
    });
    quote! {
        impl FromRequest for #name {
            type Error = Error;
            type Future = Pin<Box<dyn std::future::Future<Output = Result<Self, Self::Error>>>>;

            fn from_request(request: &HttpRequest, payload: &mut Payload) -> Self::Future {
                #(#extracts)*
                Box::pin(async move {
                    #(#awaits)*
                    Ok(Self {
                        #(#assigns,)*
                    })
                })
            }
        }
    }
}

fn render_validate(
    type_name: &str,
    name: &Ident,
    fields: &[&Field],
) -> Result<proc_macro2::TokenStream, GenerateError> {
    let mut checks = Vec::new();
    for field in fields {
        checks.extend(validate::render_checks(type_name, field)?);
    }
    if checks.is_empty() {
        return Ok(quote! {
            impl Validate for #name {}
        });
    }
    Ok(quote! {
        impl Validate for #name {
            fn validate(&self) -> Result<(), ValidationErrors> {
                Validation::new()
                    #(#checks)*
                    .finish()
            }
        }
    })
}

fn render_from_headers(name: &Ident, fields: &[&Field]) -> proc_macro2::TokenStream {
    let assigns = fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let header = attr_value(field, "header").unwrap_or(field.name.as_str());
        let missing = format!("missing header {header}");
        let not_text = format!("header {header} is not text");
        let invalid = format!("header {header} is invalid");
        if matches!(&field.ty, ast::TypeExpr::Optional(_)) {
            quote! {
                #fname: match headers.get(#header) {
                    Some(value) => Some(
                        value
                            .to_str()
                            .map_err(|_| #not_text)?
                            .parse()
                            .map_err(|_| #invalid)?,
                    ),
                    None => None,
                },
            }
        } else {
            quote! {
                #fname: headers
                    .get(#header)
                    .ok_or(#missing)?
                    .to_str()
                    .map_err(|_| #not_text)?
                    .parse()
                    .map_err(|_| #invalid)?,
            }
        }
    });
    quote! {
        impl FromRequestHeaders for #name {
            type Error = &'static str;

            fn from_headers(headers: &HeaderMap) -> Result<Self, Self::Error> {
                Ok(Self {
                    #(#assigns)*
                })
            }
        }
    }
}

fn json_field_rename(field: &Field) -> Option<String> {
    json_rename(field).map(str::to_string)
}

fn extractor_rename(field: &Field, location: Location) -> Option<String> {
    let key = match location {
        Location::Path => "path",
        Location::Query => "query",
        Location::Form => "form",
        Location::Json => "json",
        Location::Header => return None,
    };
    attr_value(field, key)
        .filter(|value| *value != field.name)
        .map(str::to_string)
}

fn is_request_type(ast: &ApiFile, name: &str) -> bool {
    ast.services.iter().any(|service| {
        service.routes.iter().any(|route| {
            route
                .request
                .as_ref()
                .and_then(request_type_name)
                .is_some_and(|req| req == name)
        })
    })
}
