use crate::request::{attr_value, request_type_name, request_views, Location, RequestViews};
use crate::util::{json_rename, pretty, rust_ident, rust_type, type_needs_hashmap};
use ast::{ApiFile, Field, TypeDef};
use quote::quote;
use syn::Ident;

pub(crate) fn render(ast: &ApiFile) -> String {
    let needs_hashmap = ast
        .types
        .iter()
        .flat_map(|def| def.fields.iter())
        .any(|field| type_needs_hashmap(&field.ty));
    let hashmap_use = needs_hashmap.then(|| quote!(use std::collections::HashMap;));
    let views: Vec<RequestViews<'_>> = ast
        .types
        .iter()
        .filter(|def| is_request_type(ast, &def.name))
        .filter_map(|def| request_views(ast, &def.name))
        .collect();
    let needs_validate = views.iter().any(|view| {
        view.is_json_only() || !view.path.is_empty() || !view.query.is_empty()
            || !view.headers.is_empty()
            || !view.form.is_empty()
            || !view.json.is_empty()
    });
    let validate_use =
        needs_validate.then(|| quote!(use rust_zero_core::{Validate, ValidationErrors};));
    let header_use = views.iter().any(|view| !view.headers.is_empty()).then(|| {
        quote! {
            use actix_web::http::header::HeaderMap;
            use rest::FromRequestHeaders;
        }
    });

    let mut items = Vec::new();
    for def in &ast.types {
        items.push(render_struct(def, json_field_rename));
        if let Some(view) = views.iter().find(|view| view.original.name == def.name) {
            if view.is_json_only() {
                items.push(render_validate(&rust_ident(&def.name)));
            } else {
                items.extend(render_views(view));
            }
        }
    }

    pretty(
        "// Code generated by rust-zero. DO NOT EDIT.\n\n",
        quote! {
            #hashmap_use
            #validate_use
            #header_use
            use serde::{Deserialize, Serialize};
            #(#items)*
        },
    )
}

fn render_struct(
    def: &TypeDef,
    rename: impl Fn(&Field) -> Option<String>,
) -> proc_macro2::TokenStream {
    let name = rust_ident(&def.name);
    let fields = def.fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let ty = rust_type(&field.ty);
        let rename = rename(field).map(|rename| quote!(#[serde(rename = #rename)]));
        quote! {
            #rename
            pub #fname: #ty,
        }
    });
    quote! {
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct #name {
            #(#fields)*
        }
    }
}

fn render_views(views: &RequestViews<'_>) -> Vec<proc_macro2::TokenStream> {
    let mut items = Vec::new();
    push_view(&mut items, views.view_ident("Path"), &views.path, Location::Path);
    push_view(
        &mut items,
        views.view_ident("Query"),
        &views.query,
        Location::Query,
    );
    push_view(
        &mut items,
        views.view_ident("Headers"),
        &views.headers,
        Location::Header,
    );
    push_view(&mut items, views.view_ident("Form"), &views.form, Location::Form);
    push_view(&mut items, views.view_ident("Body"), &views.json, Location::Json);
    items
}

fn push_view(
    items: &mut Vec<proc_macro2::TokenStream>,
    name: Ident,
    fields: &[&Field],
    location: Location,
) {
    if fields.is_empty() {
        return;
    }
    let field_tokens = fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let ty = rust_type(&field.ty);
        let rename = extractor_rename(field, location)
            .map(|rename| quote!(#[serde(rename = #rename)]));
        quote! {
            #rename
            pub #fname: #ty,
        }
    });
    items.push(quote! {
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct #name {
            #(#field_tokens)*
        }
    });
    items.push(render_validate(&name));
    if location == Location::Header {
        items.push(render_from_headers(&name, fields));
    }
}

fn render_validate(name: &Ident) -> proc_macro2::TokenStream {
    quote! {
        impl Validate for #name {
            fn validate(&self) -> Result<(), ValidationErrors> {
                Ok(())
            }
        }
    }
}

fn render_from_headers(name: &Ident, fields: &[&Field]) -> proc_macro2::TokenStream {
    let assigns = fields.iter().map(|field| {
        let fname = rust_ident(&field.name);
        let header = attr_value(field, "header").unwrap_or(field.name.as_str());
        let missing = format!("missing header {header}");
        let not_text = format!("header {header} is not text");
        let invalid = format!("header {header} is invalid");
        if matches!(&field.ty, ast::TypeExpr::Optional(_)) {
            quote! {
                #fname: match headers.get(#header) {
                    Some(value) => Some(
                        value
                            .to_str()
                            .map_err(|_| #not_text)?
                            .parse()
                            .map_err(|_| #invalid)?,
                    ),
                    None => None,
                },
            }
        } else {
            quote! {
                #fname: headers
                    .get(#header)
                    .ok_or(#missing)?
                    .to_str()
                    .map_err(|_| #not_text)?
                    .parse()
                    .map_err(|_| #invalid)?,
            }
        }
    });
    quote! {
        impl FromRequestHeaders for #name {
            type Error = &'static str;
            fn from_headers(headers: &HeaderMap) -> Result<Self, Self::Error> {
                Ok(Self {
                    #(#assigns)*
                })
            }
        }
    }
}

fn json_field_rename(field: &Field) -> Option<String> {
    json_rename(field).map(str::to_string)
}

fn extractor_rename(field: &Field, location: Location) -> Option<String> {
    let key = match location {
        Location::Path => "path",
        Location::Query => "query",
        Location::Form => "form",
        Location::Json => "json",
        Location::Header => return None,
    };
    attr_value(field, key)
        .filter(|value| *value != field.name)
        .map(str::to_string)
}

fn is_request_type(ast: &ApiFile, name: &str) -> bool {
    ast.services.iter().any(|service| {
        service.routes.iter().any(|route| {
            route
                .request
                .as_ref()
                .and_then(request_type_name)
                .is_some_and(|req| req == name)
        })
    })
}
