[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
rust-zero-core = { path = "../core" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.12", features = ["transport"] }
tonic-health = "0.12"
tower = { version = "0.4", features = ["discover"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
