[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[features]
default = []
telemetry = ["rust-zero-core/telemetry"]

[dependencies]
bytes = "1"
futures = "0.3"
http = "1"
http-body = "1"
pin-project-lite = "0.2"
prost = "0.13"
rust-zero-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.12", features = ["transport"] }
tonic-health = "0.12"
tower = { version = "0.4", features = ["discover"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
